#!/bin/sh
# Test with the debug build of `coru`.

check_tool_exists ()
{
    local tool="$1";
    local software="$2";

    if [ -z "$tool" ];
    then
        echo "No valid tool" >&2;
        exit 1;
    fi

    if ! command -v $tool 2>/dev/null 1>&2;
    then
        if [ "$software" != "" ];
        then
            echo "No $software installed on your system" >&2;
        else
            echo "No $tool installed on your system" >&2;
        fi
    fi
}

check_tool_exists sh "Bourne Shell";
check_tool_exists csh "C Shell";
check_tool_exists javac "JDK";
check_tool_exists mcs "Mono";
check_tool_exists perl "Perl";
check_tool_exists python "Python";
check_tool_exists ruby "Ruby";
check_tool_exists php "PHP";

_assert=0;
assert ()
{
    local condition=$1;

    if [ -z "$condition" ];
    then
        "No valid condition" >&2;
        exit 1;
    fi

    shift;

    if [ "$condition" -ne 0 ];
    then
        echo $@ >&2;
        _assert=1;
    fi
}

coru=./coru
test_c_by_extension ()
{
    local result="$($coru scripts/hello.c | head -n1)";

    if ! echo "$result" | fgrep "C" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_cpp_by_extension ()
{
    local result="$($coru scripts/hello.cpp | head -n1)";

    if ! echo "$result" | fgrep "C++" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_java_by_extension ()
{
    local result="$($coru scripts/HelloWorld.java | head -n1)";

    if ! echo "$result" | fgrep "Java" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_csharp_by_extension ()
{
    local result="$($coru scripts/HelloWorld.cs | head -n 1)";

    if ! echo "$result" | fgrep "C sharp" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_bourne_shell_by_extension ()
{
    local result="$($coru scripts/hello.sh | head -n1)";

    if ! echo "$result" | fgrep "Bourne" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_bourne_shell_by_shebang ()
{
    local result="$($coru scripts/helloInSh | head -n1)";

    if ! echo "$result" | fgrep "Bourne" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_c_shell_by_extension ()
{
    local result="$($coru scripts/hello.csh | head -n1)";

    if ! echo "$result" | fgrep "C Shell" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_c_shell_by_shebang ()
{
    local result="$($coru scripts/helloInCsh | head -n1)";

    if ! echo "$result" | fgrep "C Shell" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_perl_by_extension ()
{
    local result="$($coru scripts/hello.pl | head -n1)";

    if ! echo "$result" | fgrep "Perl" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_perl_by_shebang ()
{
    local result="$($coru scripts/helloInPerl | head -n1)";

    if ! echo "$result" | fgrep "Perl" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_python_by_extension ()
{
    local result="$($coru scripts/hello.py | head -n1)";

    if ! echo "$result" | fgrep "Python" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_python_by_shebang ()
{
    local result="$($coru scripts/helloInPython | head -n1)";

    if ! echo "$result" | fgrep "Python" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_ruby_by_extension ()
{
    local result="$($coru scripts/hello.rb | head -n1)";

    if ! echo "$result" | fgrep "Ruby" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_ruby_by_shebang ()
{
    local result="$($coru scripts/helloInRuby | head -n1)";

    if ! echo "$result" | fgrep "Ruby" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_php_by_extension ()
{
    local result="$($coru scripts/hello.php | head -n1)";

    if ! echo "$result" | fgrep "PHP" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

test_php_by_shebang ()
{
    local result="$($coru scripts/helloInPHP | head -n1)";

    if ! echo "$result" | fgrep "PHP" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

assert $(test_c_by_extension) "Failed to detect C by Extension";
assert $(test_cpp_by_extension) "Failed to detect C++ by Extension";
assert $(test_java_by_extension) "Failed to detect Java by Extension";
assert $(test_csharp_by_extension) "Failed to detect C sharp by Extension";
assert $(test_bourne_shell_by_extension) "Failed to detect Bourne Shell by Extension";
assert $(test_bourne_shell_by_shebang) "Failed to detect Bourne Shell by Shebang";
assert $(test_c_shell_by_extension) "Failed to detect C Shell by Extension";
assert $(test_c_shell_by_shebang) "Failed to detect C Shell by Shebang";
assert $(test_perl_by_extension) "Failed to detect Perl by Extension";
assert $(test_perl_by_shebang) "Failed to detect Perl by Shebang";
assert $(test_python_by_extension) "Failed to detect Python by Extension";
assert $(test_python_by_shebang) "Failed to detect Python by Shebang";
assert $(test_ruby_by_extension) "Failed to detect Ruby by Extension";
assert $(test_ruby_by_shebang) "Failed to detect Ruby by Shebang";
assert $(test_php_by_extension) "Failed to detect PHP by Extension";
assert $(test_php_by_shebang) "Failed to detect PHP by Shebang";

if [ $_assert -ne 0 ];
then
    exit 1;
fi

exit 0;
