#!/bin/sh

SOURCE_DIR=demo/coru
TARGET_EXEC=hello

if [ -e "$TARGET_EXEC" ];
then
    echo "$TARGET_EXEC exists on $(pwd)" >&2;
    exit 1;
fi

clean ()
{
    rm -f $TARGET_EXEC
}

coru=./dist/coru

# Test modified C code.
echo "Test modified C code";
cc=gcc
if ! command -v $cc 2>/dev/null 1>&2;
then
    echo "No GCC installed on your system" >&2;
else
    temp_src=$(mktemp).c
    $coru "${SOURCE_DIR}/hello.c" > $temp_src;
    $cc -o "$TARGET_EXEC" $temp_src || exit 1;
    ./$TARGET_EXEC >/dev/null || {
        clean;
        exit 1;
    }
    clean;
fi

# Test modified C++ code
echo "Test modified C++ code";
cxx=g++
if ! command -v $cxx 2>/dev/null 1>&2;
then
    echo "No G++ installed on your system" >&2;
else
    temp_src=$(mktemp).cpp
    $coru "${SOURCE_DIR}/hello.cpp" > $temp_src;
    $cxx -o $TARGET_EXEC $temp_src || exit 1;
    ./$TARGET_EXEC >/dev/null || {
        clean;
        exit 1;
    }
    clean;
fi

# Test modified C shell code
echo "Test modified C shell code"
if ! command -v csh 2>/dev/null 1>&2;
then
    echo "No C shell installed on your system" >&2;
else
    $coru "${SOURCE_DIR}/hello.csh" > $TARGET_EXEC
    chmod +x $TARGET_EXEC;
    ./$TARGET_EXEC >/dev/null || {
        clean;
        exit 1;
    }
    clean;
fi

# Test modified Golang code
echo "Test modified Golang code";
if ! command -v go 2>/dev/null 1>&2;
then
    echo "No Golang installed on your system" >&2;
else
    temp_src=$(mktemp).go
    $coru "${SOURCE_DIR}/hello.go" > $temp_src;
    go build -o $TARGET_EXEC $temp_src || exit 1;
    ./$TARGET_EXEC >/dev/null || {
        clean;
        exit 1;
    }
    clean;
fi

# Test modifiled JavaScript code
echo "Test modified JavaScript code";
if ! command -v node 2>/dev/null 1>&2;
then
    echo "No Node.js installed on your system" >&2;
else
    $coru "${SOURCE_DIR}/hello.js" > $TARGET_EXEC;
    chmod +x $TARGET_EXEC;
    ./$TARGET_EXEC >/dev/null || {
        clean;
        exit 1;
    }
    clean;
fi

# Test modified PHP code
echo "Test modified PHP code";
if ! command -v php 2>/dev/null 1>&2;
then
    echo "No PHP installed on your system" >&2;
else
    $coru "${SOURCE_DIR}/hello.php" > $TARGET_EXEC;
    chmod +x $TARGET_EXEC;
    ./$TARGET_EXEC >/dev/null || {
        clean;
        exit 1;
    }
    clean;
fi

# Test modified Java code
echo "Test modified Java code";
if ! command -v javac 2>/dev/null 1>&2;
then
    echo "No JDK installed on your system" >&2;
else
    cwd=$(pwd)
    temp_dir=$(mktemp -d)
    mkdir -p "${temp_dir}/com/example"
    $coru "${SOURCE_DIR}/com/example/HelloWorld.java" > "${temp_dir}/com/example/HelloWorld.java"
    javac "${temp_dir}/com/example/HelloWorld.java"
    cd "${temp_dir}" || (
        echo "Unable to move to temporary directory" >&2;
        exit 1;
    )

    java "com/example/HelloWorld" >/dev/null || {
        #rm -f HelloWorld.java HelloWorld.class;
        exit 1;
    }

    cd "$cwd"
    #rm -f HelloWorld.java HelloWorld.class
fi

exit 0;
