#!/bin/sh
# Test with the debug build of `coru`.

. ./test/common.sh

check_tool_exists ()
{
    local tool="$1";
    local software="$2";

    if [ -z "$tool" ];
    then
        echo "No valid tool" >&2;
        exit 1;
    fi

    if ! command -v $tool 2>/dev/null 1>&2;
    then
        if [ "$software" != "" ];
        then
            echo "No $software installed on your system" >&2;
        else
            echo "No $tool installed on your system" >&2;
        fi
    fi
}

check_tool_exists sh "Bourne Shell";
check_tool_exists csh "C Shell";
check_tool_exists javac "JDK";
check_tool_exists mcs "Mono";
check_tool_exists perl "Perl";
check_tool_exists python "Python";
check_tool_exists ruby "Ruby";
check_tool_exists php "PHP";
check_tool_exists go "Golang";
check_tool_exists rustc "Rust";
check_tool_exists swift "Swift";

coru=./dist/coru
detect_c_by_extension ()
{
    local result="$($coru demo/hello.c | head -n 1)";

    if ! echo "$result" | fgrep "C" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_cpp_by_extension ()
{
    local result="$($coru demo/hello.cpp | head -n1)";

    if ! echo "$result" | fgrep "C++" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_java_by_extension ()
{
    local result="$($coru demo/HelloWorld.java | head -n1)";

    if ! echo "$result" | fgrep "Java" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_csharp_by_extension ()
{
    local result="$($coru demo/HelloWorld.cs | head -n 1)";

    if ! echo "$result" | fgrep "C sharp" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_bourne_shell_by_extension ()
{
    local result="$($coru demo/hello.sh | head -n1)";

    if ! echo "$result" | fgrep "Bourne" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_bourne_shell_by_shebang ()
{
    local result="$($coru demo/helloInSh | head -n1)";

    if ! echo "$result" | fgrep "Bourne" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_c_shell_by_extension ()
{
    local result="$($coru demo/hello.csh | head -n1)";

    if ! echo "$result" | fgrep "C Shell" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_c_shell_by_shebang ()
{
    local result="$($coru demo/helloInCsh | head -n1)";

    if ! echo "$result" | fgrep "C Shell" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_perl_by_extension ()
{
    local result="$($coru demo/hello.pl | head -n1)";

    if ! echo "$result" | fgrep "Perl" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_perl_by_shebang ()
{
    local result="$($coru demo/helloInPerl | head -n1)";

    if ! echo "$result" | fgrep "Perl" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_python_by_extension ()
{
    local result="$($coru demo/hello.py | head -n1)";

    if ! echo "$result" | fgrep "Python" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_python_by_shebang ()
{
    local result="$($coru demo/helloInPython | head -n1)";

    if ! echo "$result" | fgrep "Python" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_ruby_by_extension ()
{
    local result="$($coru demo/hello.rb | head -n1)";

    if ! echo "$result" | fgrep "Ruby" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_ruby_by_shebang ()
{
    local result="$($coru demo/helloInRuby | head -n1)";

    if ! echo "$result" | fgrep "Ruby" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_php_by_extension ()
{
    local result="$($coru demo/hello.php | head -n1)";

    if ! echo "$result" | fgrep "PHP" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_php_by_shebang ()
{
    local result="$($coru demo/helloInPHP | head -n1)";

    if ! echo "$result" | fgrep "PHP" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_js_by_extension ()
{
    local result="$($coru demo/hello.js | head -n 1)";

    if ! echo "$result" | fgrep "JavaScript" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_js_by_shebang ()
{
    local result="$($coru demo/helloInJS | head -n 1)";

    if ! echo "$result" | fgrep "JavaScript" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_golang_by_extension ()
{
    local result="$($coru demo/hello.go | head -n 1)";

    if ! echo "$result" | fgrep "Golang" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_rust_by_extension ()
{
    local result="$($coru demo/hello.rs | head -n 1)";

    if ! echo "$result" | fgrep "Rust" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_objc_by_extension ()
{
    local result="$($coru demo/hello.m | head -n 1)";

    if ! echo "$result" | fgrep "Objective-C" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_objcpp_by_extension ()
{
    local result="$($coru demo/hello.mm | head -n 1)";

    if ! echo "$result" | fgrep "Objective-C++" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_swift_by_extension ()
{
    local result="$($coru demo/hello.swift | head -n 1)";

    if ! echo "$result" | fgrep "Swift" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

detect_swift_by_shebang ()
{
    local result="$($coru demo/helloInSwift | head -n 1)";

    if ! echo "$result" | fgrep "Swift" >/dev/null;
    then
        echo 1;
        return 1;
    fi

    echo 0;
}

assert $(detect_c_by_extension) "Failed to detect C by extension";
assert $(detect_cpp_by_extension) "Failed to detect C++ by extension";
assert $(detect_java_by_extension) "Failed to detect Java by extension";
assert $(detect_csharp_by_extension) "Failed to detect C sharp by extension";
assert $(detect_bourne_shell_by_extension) "Failed to detect Bourne Shell by extension";
assert $(detect_bourne_shell_by_shebang) "Failed to detect Bourne Shell by Shebang";
assert $(detect_c_shell_by_extension) "Failed to detect C Shell by extension";
assert $(detect_c_shell_by_shebang) "Failed to detect C Shell by Shebang";
assert $(detect_perl_by_extension) "Failed to detect Perl by extension";
assert $(detect_perl_by_shebang) "Failed to detect Perl by Shebang";
assert $(detect_python_by_extension) "Failed to detect Python by extension";
assert $(detect_python_by_shebang) "Failed to detect Python by Shebang";
assert $(detect_ruby_by_extension) "Failed to detect Ruby by extension";
assert $(detect_ruby_by_shebang) "Failed to detect Ruby by Shebang";
assert $(detect_php_by_extension) "Failed to detect PHP by extension";
assert $(detect_php_by_shebang) "Failed to detect PHP by Shebang";
assert $(detect_js_by_extension) "Failed to detect JavaScript by extension";
assert $(detect_js_by_shebang) "Failed to detect JavaScript by Shebang";
assert $(detect_golang_by_extension) "Failed to detect Golang by extension";
assert $(detect_rust_by_extension) "Failed to detect Rust by extension";
assert $(detect_objc_by_extension) "Failed to detect Objective-C by extension";
assert $(detect_objcpp_by_extension) "Failed to detect Objective-C++ by extension";
assert $(detect_swift_by_extension) "Failed to detect Swift by extension";
assert $(detect_swift_by_shebang) "Failed to detect Swift by shebang";

assertAll;
